### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by casalot** [expandjs/expandjs-starter-kit#2]
Release 1.0.1 solved the installation problems, but now I'm getting the following when running `npm run build`:
```
{ err:
   { message: 'SyntaxError: Unexpected token punc «(», expected punc «:»',
     filename: 0,
     line: 73,
     col: 25,
     pos: 1766,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)\n    at expect_token (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:9)\n    at expect (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2116:36)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2689:13)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2139:24)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2619:35)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2795:19)' } }
warn:    Unable to optimize .js file /Users/cas/source/xp-starter-kit/bower_components/xp-elements/xp-selector-multi-behavior.html_script_0.js
```

**Comment by Pupix** [comment]
Can't reproduce this problem. Do you have the latest version of `polymer-cli` installed?

**Comment by casalot** [comment]
I double-checked, and I have polymer-cli `0.17.0` installed.

**Comment by Pupix** [comment]
That seems to be just a warning, not an error.

There's nothing we can do about it at the moment since UglifyJS doesn't support ES6 yet. They are actively working on it and once that's released and `polymer-cli` gets updated all the warnings will go away.

**Comment by casalot** [comment]
Okay, cool.

How is the app accessed? I've ran `node server`, and then got to `http://localhost:3000` in the browser. But, then I get `ERR_EMPTY_RESPONSE`.

Am I missing a step?

**Comment by Pupix** [comment]
It's `https` not `http`. The first time you visit you may receive an SSL error because you are on a local server.

If you don't see any text, clean your bower's cache with `bower cache clean` and redo `bower install`.
